### ISSUE TITLE
Open source of dataset

### ISSUE THREAD

**Issue by lin-yao-yue** [deguchihiroyuki/E2GS#2]
The quality of your work is truly impressive!
I encountered issues when using COLMAP and EDI to generate point clouds. So I am wondering if datasets that directly supports 3D GS used in paper could be provided.
Thank you very much.

**Comment by lin-yao-yue** [comment]
The point cloud obtained using COLMAP initialization and the point cloud obtained from E2GS training are not on the same scale, which has led to poor training results. 
Does the provided current version of the code have any issues, or could you directly provide the dataset used for training with the current code?

**Comment by deguchihiroyuki** [comment]
@lin-yao-yue, thanks for raising a discussion! So, I will provide the dataset used for the input.

By the way, I create the initial point cloud like the way below.

1. Using "colmap gui"
2. Doing "automatic reconstruction"
3. After finishing it, "\dense\0\sparse\points3D.bin" shoould be made, and use it as an initial pointcloud.

Even if inputs are the E2NeRF's blurry images, I think it would work. So please try to do so!
