### ISSUE TITLE
Problem about the train_cameras

### ISSUE THREAD

**Issue by KHao123** [deguchihiroyuki/E2GS#3]
Thanks for the nice work!
For the synthesis dataset, 100 views are used for training. But I got 200 views when training.
It seems that these [(lines)](https://github.com/deguchihiroyuki/E2GS/blob/3fa5d5f8602c0e200c52d77c2b4f0a7c60d35432/scene/dataset_readers.py#L321) concate the train_cam_infos and test_cam_infos.

Is it a bug? It is strange to train with test_cam_infos.

**Comment by deguchihiroyuki** [comment]
@KHao123 , thanks for raising a discussion!  Certainly, it is strange, so I will delete these lines.
And I confirmed that these lines don't affect the output because in E2NeRF dataset, the contents of transform_train.json and transform_test.json  are exactly the same

**Comment by KHao123** [comment]
Although the camera poses are the same, the images corresponding to the train and test set are different, which will be used to calculate the blur image loss.
The ground truth comes from both the blurred and clear images, which are shown in the tensorboard.

**Comment by deguchihiroyuki** [comment]
Oh, I see. So, it`s a bug. I corrected the codes.
And I remembered that when I was experimenting on myself, I had also set the test set image to a blurred image...
@KHao123, thank you again for reporting a bug!

**Comment by KHao123** [comment]
Thanks for your reply!
My issue is solved.
